### ISSUE TITLE
Alarms and timers

### ISSUE THREAD

**Issue by ryan-esty** [nicholasjconn/python-alexa-voice-service#8]
I've been looking for a way to do the latest API version of AVS using curl or something that didn't require java and I ran into this. I'm running on Linux and for the most part it is working except for timers and alarms.

When I set the timer or alarm I don't see anything in the downstream channel. I was under the impression that I would see something in this channel if a timer or an alarm was set.

Has anyone else tried this? Am I correct I should be focused in on looking at the downstream_thread?

**Comment by ryan-esty** [comment]
After doing some more bumbling around (python isn't my main language) there might be an issue with read_from_downstream. It always returns nothing even though there is down stream data present. If I change the code to make new_data to be the last element in the list and data to be the rest things work. Did something change since this part was last used or am I doing something wrong?

**Comment by tgarc** [comment]
I may be totally off base but the AVS docs say you need to POST a SynchronizeState directive before you can start receiving downstream message which the current code doesn't seem to do:

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/managing-an-http-2-connection#create

**Comment by ryan-esty** [comment]
Thanks I tried some more but it didn't do much. It seems I only get the downstream when I change the alarm through the alexa.amazon.com interface. If I speak the timer or alarm I don't get it at all.
